# core/report/html_template.py
from __future__ import annotations

from typing import Dict


class HTMLTemplate:
    """Membangun halaman HTML laporan profesional dengan CSS modern."""

    @staticmethod
    def build(data: Dict) -> str:
        target = data.get("target", "Unknown")
        sections = ""

        # Modul sections
        for module, results in data.get("scans", {}).items():
            sections += HTMLTemplate._module_section(module, results)

        # AI Analysis section
        if "ai_analysis" in data:
            sections += HTMLTemplate._ai_section(data["ai_analysis"])

        # Export files section
        if data.get("export_files"):
            sections += HTMLTemplate._export_section(data["export_files"])

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>OSINT Report – {target}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f0f2f5; padding: 40px; color: #212529; }}
.header {{ background: linear-gradient(135deg, #0d6efd, #6610f2); color: white; padding: 35px; border-radius: 10px; margin-bottom: 30px; }}
.header h1 {{ font-size: 2em; }}
.header p {{ margin-top: 8px; opacity: 0.9; }}
.module {{ background: white; border-radius: 8px; padding: 25px; margin-bottom: 25px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
.module h2 {{ color: #0d6efd; border-bottom: 3px solid #6610f2; padding-bottom: 10px; margin-bottom: 20px; }}
table {{ width: 100%; border-collapse: collapse; }}
th, td {{ padding: 10px 12px; text-align: left; border-bottom: 1px solid #dee2e6; font-size: 0.9em; }}
th {{ background: #e9ecef; font-weight: 600; }}
.badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 0.8em; font-weight: 600; }}
.found {{ background: #d4edda; color: #155724; }}
.notfound {{ background: #f8d7da; color: #721c24; }}
.error {{ background: #fff3cd; color: #856404; }}
.ai-section {{ background: linear-gradient(135deg, #f1f3f5, #e9ecef); padding: 30px; border-radius: 8px; margin-top: 30px; }}
.ai-section h2 {{ color: #6610f2; }}
.risk-high {{ color: #dc3545; font-weight: bold; }}
.risk-medium {{ color: #fd7e14; font-weight: bold; }}
.risk-low {{ color: #198754; font-weight: bold; }}
.score {{ font-size: 2em; font-weight: bold; color: #0d6efd; }}
.footer {{ text-align: center; margin-top: 40px; color: #6c757d; font-size: 0.85em; }}
</style>
</head>
<body>
<div class="header">
<h1>🕵️ OSINT Fusion Intelligence Report</h1>
<p><strong>Target:</strong> {target}</p>
<p><strong>Generated:</strong> {data.get('generated_at', 'N/A')}</p>
</div>
{sections}
<div class="footer">Generated by OSINT Fusion &copy; 2026</div>
</body>
</html>"""

    @staticmethod
    def _module_section(module: str, results: list) -> str:
        rows = ""
        for r in results:
            status = r.get("status", "")
            badge_class = "found" if status == "FOUND" else "notfound" if status == "NOT_FOUND" else "error"
            rows += (
                f"<tr>"
                f"<td>{r.get('platform', '')}</td>"
                f"<td>{r.get('username', '')}</td>"
                f"<td><span class='badge {badge_class}'>{status}</span></td>"
                f"<td style='max-width:200px;overflow:hidden;text-overflow:ellipsis;'>{r.get('url', '')}</td>"
                f"<td>{r.get('confidence', 0):.2f}</td>"
                f"<td>{r.get('intelligence_score', 0):.1f}</td>"
                f"</tr>"
            )
        return f"""
<div class="module">
<h2>{module.upper()} Intelligence</h2>
<table>
<tr><th>Platform</th><th>Username</th><th>Status</th><th>URL</th><th>Confidence</th><th>Intel Score</th></tr>
{rows}
</table>
</div>"""

    @staticmethod
    def _ai_section(ai_data: dict) -> str:
        if isinstance(ai_data, dict):
            analysis = ai_data.get("ai_analysis", ai_data)
        else:
            analysis = {}
        risk = analysis.get("risk_level", "unknown").lower()
        risk_class = "risk-high" if risk in ("high", "critical") else "risk-medium" if risk == "medium" else "risk-low"
        return f"""
<div class="ai-section">
<h2>🤖 AI Analysis</h2>
<p><strong>Risk Level:</strong> <span class="{risk_class}">{risk.upper()}</span></p>
<p><strong>Risk Score:</strong> <span class="score">{analysis.get('risk_score', 0)}/100</span></p>
<p><strong>Summary:</strong> {analysis.get('summary', 'N/A')}</p>
<p><strong>Correlations:</strong> {', '.join(analysis.get('correlations', []))}</p>
<p><strong>Suspicious Findings:</strong> {', '.join(analysis.get('suspicious_findings', []))}</p>
<p><strong>Insights:</strong> {', '.join(analysis.get('insights', []))}</p>
<p><strong>Narrative:</strong></p>
<p>{analysis.get('narrative', 'N/A')}</p>
</div>"""

    @staticmethod
    def _export_section(export_files: dict) -> str:
        items = ""
        for category, files in export_files.items():
            if isinstance(files, dict):
                for name, path in files.items():
                    if isinstance(path, str):
                        items += f"<li><strong>{category}/{name}:</strong> {path}</li>"
        return f"""
<div class="module">
<h2>📁 Exported Files</h2>
<ul>{items}</ul>
</div>"""